In [1]:
import torch

In [2]:
# (b, num_heads, num_tokens, head_dim) = (1, 2, 3, 4)

a = torch.tensor(
    [ # 1st dim => 1 Element Inside It
        [ # 2nd dim => 2 Element Inside It
            [ # 3rd dim => 3 Element Inside It
                [0.2745, 0.6584, 0.2775, 0.8573], # 4th dim => 4 Element Inside It
                [0.8993, 0.0390, 0.9268, 0.7388],
                [0.7179, 0.7058, 0.9156, 0.4340]
            ],
    
            [
                [0.0772, 0.3565, 0.1479, 0.5331],
                [0.4066, 0.2318, 0.4545, 0.9737],
                [0.4606, 0.5159, 0.4220, 0.5786]
            ]
        ]
    ])

In [9]:
print("Original Matrix:\n\n", a, end="\n\n")
print("Transposed Matrix:\n\n", a.transpose(2, 3), end="\n\n")

Original Matrix:

 tensor([[[[0.2745, 0.6584, 0.2775, 0.8573],
          [0.8993, 0.0390, 0.9268, 0.7388],
          [0.7179, 0.7058, 0.9156, 0.4340]],

         [[0.0772, 0.3565, 0.1479, 0.5331],
          [0.4066, 0.2318, 0.4545, 0.9737],
          [0.4606, 0.5159, 0.4220, 0.5786]]]])

Transposed Matrix:

 tensor([[[[0.2745, 0.8993, 0.7179],
          [0.6584, 0.0390, 0.7058],
          [0.2775, 0.9268, 0.9156],
          [0.8573, 0.7388, 0.4340]],

         [[0.0772, 0.4066, 0.4606],
          [0.3565, 0.2318, 0.5159],
          [0.1479, 0.4545, 0.4220],
          [0.5331, 0.9737, 0.5786]]]])



In [11]:
print("Original Matrix Shape \t=>", a.shape)
print("Transposed Matrix Shape =>", a.transpose(2, 3).shape)

Original Matrix Shape 	=> torch.Size([1, 2, 3, 4])
Transposed Matrix Shape => torch.Size([1, 2, 4, 3])


In [18]:
print("Matrix Multiplication Result:\n\n", a @ a.transpose(2, 3), end="\n\n")
print("Matrix Shape =>", (a @ a.transpose(2, 3)).shape)

Matrix Multiplication Result:

 tensor([[[[1.3208, 1.1631, 1.2879],
          [1.1631, 2.2150, 1.8424],
          [1.2879, 1.8424, 2.0402]],

         [[0.4391, 0.7003, 0.5903],
          [0.7003, 1.3737, 1.0620],
          [0.5903, 1.0620, 0.9912]]]])

Matrix Shape => torch.Size([1, 2, 3, 3])


In [19]:
first_head = a[0, 0, :, :]
second_head = a[0, 1, :, :]

In [22]:
print("First Head:\n\n", first_head, end="\n\n")
print("Second Head:\n\n", second_head)

First Head:

 tensor([[0.2745, 0.6584, 0.2775, 0.8573],
        [0.8993, 0.0390, 0.9268, 0.7388],
        [0.7179, 0.7058, 0.9156, 0.4340]])

Second Head:

 tensor([[0.0772, 0.3565, 0.1479, 0.5331],
        [0.4066, 0.2318, 0.4545, 0.9737],
        [0.4606, 0.5159, 0.4220, 0.5786]])


In [23]:
first_res = first_head @ first_head.T
second_res = second_head @ second_head.T

In [25]:
print("First Head Result:\n\n", first_res, end="\n\n")
print("Second Head Result:\n\n", second_res)

First Head Result:

 tensor([[1.3208, 1.1631, 1.2879],
        [1.1631, 2.2150, 1.8424],
        [1.2879, 1.8424, 2.0402]])

Second Head Result:

 tensor([[0.4391, 0.7003, 0.5903],
        [0.7003, 1.3737, 1.0620],
        [0.5903, 1.0620, 0.9912]])
